language: rust
sudo: false

after_success:
  - curl https://stainless-steel.github.io/travis/after_success.sh | bash

env:
  global:
    secure: u2cCWB+TYzwrMXP+oEGSeXRfosPrhUiEZO5FA+jTE+2jvMIdWHFEUpWQwdxjmijU9yum64qmj8aqjIMu9ALGNbzy5hCPMikrI/AaN88e+Lv5vOa2dSBALxOpmTPv5G+9L+CzCvwAdZirDIgBPQmAsdpqttq3jV/6DlgQDDwJ7vXA6m+QJfF6h9XkCUHJYZu5kUQ3lPLgTZmfmWj5ruhc9CImNUcppkysLCStrLTm6t40qGpb74wEu8dfWKvgKhordfthf53eK4HTu/+dWS36Gl2Jv268a3LN7OGm41Q3lkQdgOr9H4rlEFByZbVAV3kLLkC+vgzsWYPoQMbbUoR2mNBEzdhOv2WoT7YS/iyyddeUSrZP/4h2SYhXsKv1E1oiLcl0IExEfiJL82bcC5h3FVMxIX5CK4VcAYkf3jsvcfcF54RlTRjCS3mu0wnfSRfFBmrnYHYoQS7OlA7VAo2q9gQxqiCRwtjqe2AGyC/5+rErxUbUIGa3nsMVtVwY7ihP0jtPrP/UB5j7fAog/e1WNGS+XP3ohn6KFfQpilmxRI49TIdkRdir7BfUkMCrCQEDgFU05Yqc36dWiUNNDdaDD1dMgV9R+Ore3i+zMXE5esJfHzBLkJv6tXRx+4+WsrWAraYp6BZcJhP77Wblpx46ZoWsxPGP1mH3OFiXShaiV6U=

notifications:
  email: false
